### ISSUE TITLE
关于那个canGoBack的我这边调用了还是会崩溃

### ISSUE THREAD

**Issue by babystyles** [xorshine/GSWebView#1]
![image](https://cloud.githubusercontent.com/assets/19380282/19422984/5b63de1a-944e-11e6-8404-07bbe71968fd.png)

**Comment by babystyles** [comment]
我这是在模拟器上测试的 真机没试

**Comment by BeatsKitano** [comment]
刚刚修复了，试试看。

**Comment by babystyles** [comment]
好，这个已经可以了，我有个问题想请教下：就是如果WebView和JS交互拿数据，这个数据很大，app在获取这个数据的时候有时会造成app闪退，你有没有什么方案或者思路可以参考的。

**Comment by BeatsKitano** [comment]
其实你有看到Demo中，JS传来的数据只是一个字典，数据的交互极其微弱。想知道的是，JS需要传给你的数据是什么，能大到怎样的程度？至今还未碰到这种情况下的崩溃问题，能否查看一下crash日志？再次谢谢你找出的问题，在自己未集成的情况下，你帮我踩了这些坑，过意不去。

**Comment by babystyles** [comment]
那个数据是通过网页生成的图片的base64编码（原图所以可能比较大），图片过多时就会造成闪退（100张），但是这个并不是你这个框架的问题，因为我用原生的UIWebView和WKWebView图片过多也是会崩溃的，我只是想想请教下有没有什么思路可以解决这个问题，iOS这边我得到的这个数据很大，我应该怎么来处理？

**Comment by babystyles** [comment]
闪退的原因，是内存过大

**Comment by BeatsKitano** [comment]
即使是我司的社交聊天功能，发送图片时，也最多只是上传9张，微信做到了十张，因为一次性将这么多图片加入内存，很容易受到警告
