### ISSUE TITLE
有两个问题

### ISSUE THREAD

**Issue by yexiwen** [xorshine/GSWebView#2]
1、- (instancetype)initWithFrame:(CGRect)frame JSPerformer:(nonnull id)performer
{
    if (self = [super initWithFrame:frame]) {
        _pointers = [NSPointerArray weakObjectsPointerArray];
        [_pointers addPointer:(__bridge void * _Nullable)(performer)];
        if ([UIDevice currentDevice].systemVersion.doubleValue >= 9.0){
            [self configureWKWebViewWithFrame:frame];
        }else{
            [self configureUIWebViewWithFrame:frame];
        }
    }
    return self;
}

应该是[UIDevice currentDevice].systemVersion.doubleValue >= 8.0
2、JS掉OC没有传参数，类似- (void)getConsultationInfo:(NSDictionary *)param这样的方法不会响应
3、之前的版本内存释放不了，貌似这个版本解决了？

**Comment by BeatsKitano** [comment]
9.0是因为HTTPs
内存问题是指UIWebView吗？倘若是，这就是苹果为何使用WebKit的原因

**Comment by yexiwen** [comment]
addScriptMessageHandler 没有remove导致内存泄漏，你看怎么处理下

**Comment by BeatsKitano** [comment]
已更新
