### ISSUE TITLE
这里当webView是WKWebView的时候应该会执行两次吧

### ISSUE THREAD

**Issue by maocomen** [xorshine/GSWebView#4]
- (void)loadRequest:(NSURLRequest *)request
{
    _request = request;
    if ([_webView isKindOfClass:[WKWebView class]])
        [(WKWebView *)_webView loadRequest:request];
    [(UIWebView *)_webView loadRequest:request];
}

**Comment by BeatsKitano** [comment]
谢谢，已修复
